version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: broker
    ports:
      - "1884:1883"   # MQTT 기본 포트
      - "9001:9001"   # 웹소켓 (옵션)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - helper_net
  python-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - mosquitto
    networks:
      - helper_net

networks:
  mqtt_net:
    driver: bridge
